### ISSUE TITLE
Consistent pagination across browsers

### ISSUE THREAD

**Issue by yh54321** [futurepress/epub.js#1033]
Is it possible to achieve a consistent pagination for a book across all browsers. That is, the book will have the same number of pages, and each page will have the same content regardless of the browsers it is being viewed on?

When I render a book into a div of given dimensions, it appears the same whenever the same browser is used (Chrome). If I open it in Firefox or in a mobile browser, the pagination is slightly different due to slight variations in CSS element sizes.

**Can this be overcome in any way to ensure consistent pagination across all browsers?**

**Comment by Juul** [comment]
You would have to manually specify where the page breaks should occur in the ebook using e.g. `break-before` CSS rules (which I _think_ are supported by epub.js but I'm not 100% certain. The result would then only look correct when viewing the book in the window size for which it was created.

Different browsers use different rendering engines and they are simply never going to be accurate to within a pixel in all cases. Since even a single pixel difference can cause a difference in page break location what you're asking is not really possible without manually specifying where to break the pages. I'm curious what the use case is though.
