### ISSUE TITLE
Page cut off at bottom when using `scrolled-doc` and `scrolled` after commit 7001f86

### ISSUE THREAD

**Issue by johnfactotum** [futurepress/epub.js#1065]
Commit 7001f86 removed line 187 to 189 from `content.js`:
https://github.com/futurepress/epub.js/blob/26075c2d498a88843f97ca359c88f7261659db8c/src/contents.js#L187-L189

And now the text is cut off at the bottom when using `scrolled-doc` and `scrolled`.

Using 0.3.87, `examples/scrolled.html` looks like this:
![image](https://user-images.githubusercontent.com/50942278/82814966-b43ea780-9e87-11ea-9b28-3abd69273ee8.png)

Using latest code on master:
![image](https://user-images.githubusercontent.com/50942278/82815001-c3255a00-9e87-11ea-85f6-f3124afe1ba2.png)

**Comment by fchasen** [comment]
Yikes, thanks for catching this. I'm working on setting up visual regression test that should identify these type of bugs in the future.

I updated the code for calculating the size to handle vertical rtl text and it removed the padding calculation for this view. Still trying to find a way to make both text flows happy...

**Comment by johnfactotum** [comment]
With the latest fix, the offset goes wrong when viewing the last column of vertical text.

Screen recording of viewing the sample [vertical writing EPUB](https://github.com/IDPF/epub3-samples/releases/download/20170606/mymedia_lite.epub) from [EPUB 3 samples](https://idpf.github.io/epub3-samples/30/samples.html) with `examples/input.html` on WebKitGTK:

![Peek 2020-06-04 11-15](https://user-images.githubusercontent.com/50942278/83711090-cb149500-a611-11ea-9f21-d78ee7d4b83e.gif)

**Comment by fchasen** [comment]
Don't have a good way to reproduce this locally yet, but I tested on Linux and am seeing the offset. No idea why this isn't happening on Chrome / Firefox / Safari but it seems like the issue is that the height of the view isn't divisible into the pages anymore.

Height for the chapter reports as `3563` but it should be increased to `3600`. Should just need to do something similar to how we increase the size for paginated horizontal pages, but will need to make sure this only happens for vertical paginated books.

A quick test is on the `1065_vertical_rounding` branch:
https://github.com/futurepress/epub.js/blob/abe19c15f0b68fb7dc9c63cc5ce7ad9a348586d6/src/managers/views/iframe.js#L295-L299

**Comment by bksubhuti** [comment]
We have the same problem.. I'd love to have the x scroll hidden.. I think that would fix it but I cannot hide the scroll bar in css.
            overflow-y: scroll;
            overflow-x: hidden;

so how to adjust the height the extra 7 pixels.?
btw:  great library.. saved us tons of time

**Comment by johnfactotum** [comment]
Just tried 0.3.88. Everything seems to be fixed now. No problem with vertical writing, either.
