### ISSUE TITLE
How to display single html like ebook viewer without create epub file

### ISSUE THREAD

**Issue by winterdl** [futurepress/epub.js#1143]
I've read the source code, Rendition will render with data from Book, but I dont know how to render a single html page as ebook viewer with pagination, font options and theme without create epub file.

**Comment by johnfactotum** [comment]
Epub.js supports [webpub](https://github.com/readium/webpub-manifest), which means that you can use a JSON file and specify URLs to HTML files, and render them as a book, by using `book.openManifest()`.

Render inline HTML code (as opposed to HTML files) is a bit more involved. I tried making a webpub manifest with blob URLs, but it didn't work due to how Epub.js processes URLs. So I ended up adding a new method to `Book` that feeds the JSON object directly to `Packaging`, as well as a couple other patches for it to work.
