### ISSUE TITLE
Vertical writing is displayed incorrectly when page progression direction is rtl

### ISSUE THREAD

**Issue by tjmtmmnk** [futurepress/epub.js#1257]
When the page progression direction is rtl and the iframe viewer's body writingMode is horizontal and the text writingMode is vertical-rl, the display is incorrect. (e.g. https://codepen.io/tjmtmmnk/pen/KKZPaZY )

This is sample epub ([sample-epub.zip](https://github.com/futurepress/epub.js/files/8249248/sample-epub.zip)) that reproduce this issue.

The problem may be due to the fact that Japanese is the language of ltr, whereas `writing-mode: horizontal-tb; direction: rtl;` is specified in the parent element. ([reproduce this implementation](https://github.com/futurepress/epub.js/blob/master/src/contents.js#L1061))

Therefore, we have confirmed that the following change solves the problem.

```css
 .japanese {
   writing-mode: vertical-lr;
   direction: ltr;
 }
```

I believe the following implementation is needed [around here](https://github.com/futurepress/epub.js/blob/master/src/contents.js#L1061) to solve the above problems.

```js
const toBeReversed = (dir === "rtl" && (axis === "horizontal" || axis === "vertical-lr") || (dir === "ltr" && axis === "vertical-rl");
 
 if(toBeReversed) {
   document.querySelectorAll("body > *").forEach(ele => {
     const isLTR = detectLTR(detectLanguage(ele.innerText)) // detectLTR, detectLanguage: to be implemented
     const direction = isLTR ? "ltr" : "rtl";
     ele.style.direction = direction;  
   });
 }
```

If this change is deemed appropriate, I would like to send a Pull Request. Thank you!

**Comment by johnfactotum** [comment]
I think there are two different problems at play here. One is that Epub.js forces the direction of all content documents to be the same as `page-progression-direction`. The second problem is the handling of `writing-mode` when it's not set on the root element.

The first problem is due to the fact that, with multicolumn-based pagination, it's impossible to have LTR text flow in RTL columns unless you use the Webkit-only non-standard property `-webkit-column-progression`. So to ensure a consistent page progression direction, the only way is to set the text direction to be the same as `page-progression-direction`. This is a limitation of CSS columns.

The proper solution would be to use the `page-progression-direction` to set `-webkit-column-progression` instead of `direction`. This is I think essentially how Apple Books does it. And it's really the only way to have horizontal LTR text flow correctly in a book with RTL page progression. Note that in your case, although the main body text is vertical, the wirting mode of the root element is horizontal, so technically it's *not* vertical writing, but horizontal.

Which brings us to the second problem. Where one sets `writing-mode` is significant. The writing mode of the root element is called the [*principal writing mode*](https://drafts.csswg.org/css-writing-modes/#principal-flow), and it's used to determine how the content is paginated. Setting `writing-mode: vertical-rl;` on the root element tells Epub.js to paginate content in a way that is appropriate for vertical text, which is very different from how it would paginate horizontal text. Setting it on a child element only affects the flow within that particular element, not the overall flow of the page.

So in your case, to work around the problem, one should probably override the principle writing based on `dc:language` and `page-progression-direction`. That is if it's a CJK book with `page-progression-direction` set to `rtl`, then in all probability (though it's not certain) the book is meant to be displayed with its principle writing mode set to `vertical-rl`. Properly speaking, though, this should not be necessary. The fault is with the EPUB's creator who should have set the principle writing mode correctly.

**Comment by tjmtmmnk** [comment]
Thank you for your kind support!

So you are saying that we will need such a hook as a workaround?

```js
rendition.hooks.content.register((contents, rendition) => {
  if(isCJK && book.package.metadata.direction === "rtl") { // isCJK: to be implemented
      const WRITING_MODE = prefixed("writing-mode"); // prefixed: implemented in core.js
      contents.document.documentElement.style[WRITING_MODE] = "vertical-rl";
      contents.document.documentElement.style["direction"] = '';
      rendition.manager.layout.format(contents);
    }
});
```

I have confirmed that the above code will result in the intended display.

**Comment by johnfactotum** [comment]
Yes, something like that is what I have in mind. Probably also need exclude fixed layout books. That is, only apply the style if `layout !== 'pre-paginated'`

**Comment by tjmtmmnk** [comment]
> Probably also need exclude fixed layout books.

oh, that's right.

Thank you for helping me many times!
