### ISSUE TITLE
Issue with react and hosted enviroment

### ISSUE THREAD

**Issue by nickmackenzie** [futurepress/epub.js#1312]
Hello, I have a working version locally intergrated with react in how I want to display but when I go to host and test it live, the epub does not render. I'm just rendering the epub in a useEffect. Is there a better way?

```
useEffect(() => {            
        const book = ePub("./sample.epub");        
        const rendition = book.renderTo("area", { flow: 'paginated', width: '100%', height: '100%' });        
        rendition.display();         
    }, []);
```
    
I think rendition.display() is running before the epub has a chance to download.
Any tips on playing with react nicely?

**Comment by Hafizur046** [comment]
Hi, to do any kind of DOM manipulation useLayoutEffect is better suited than useEffect because it runs synchronously after the component is rendered as well as blocking the render process while its running, as the react.js [doc](https://reactjs.org/docs/hooks-reference.html#uselayouteffect) states 

> The signature is identical to useEffect, but it fires synchronously after all DOM mutations. Use this to read layout from the DOM and synchronously re-render. Updates scheduled inside useLayoutEffect will be flushed synchronously, before the browser has a chance to paint.

I've tried using useEffect and got a similar result as you did, the div did not finish rendering when the rendition.display() tried to render the epub and failed to display it. Simply switching the useEffect to useLayoutEffect solves the issue:
```
  useLayoutEffect(() => {
    const book = ePub("./.epub");
    const rendition = book.renderTo("area", {
      flow: "paginated",
      width: "100%",
      height: "100%",
    });
    rendition.display();
  }, []);
```

**Comment by nickmackenzie** [comment]
@Hafizur046 Thanks for the reply! Have you tested this on a hosted enviroment? I have made the change to useLayoutEffect but I'm still getting the same results.

**Comment by desmondsmall** [comment]
Hey, check out these two repositories for reference. You need to initialize using an async function. 

https://github.com/gerhardsletten/react-reader

https://github.com/gerhardsletten/react-reader

**Comment by nickmackenzie** [comment]
@desmondsmall Thanks for this. That helped a bunch. Issue resolved.
