### ISSUE TITLE
Inflate with IOS

### ISSUE THREAD

**Issue by softroots** [futurepress/epub.js#142]
Is there a known problem with the inflate feature for a compressed ePub file on the iOS (7.1 - which is the only platform I currently am using for test) platform? It appears that may be the case. I have verified the location (in persistent storage) to be correct for the ePub that I am trying to access. I am able to access PDF files in the same location without any problem. However, the ePub files never load - they just keep trying to.

I have also tried the render-refactor branch (based on a another previous issue #114 regarding what appears to be the same problem) with no success. I have also tried multiple ePub files ranging from < 1M to 20M in size - all displaying same problem.

Any suggestions are appreciated.

**Comment by MaxDaten** [comment]
currently same problem on iOS 8 in an Ionic Framework App (in a WebView). In a desktop or mobile browser every epub file I tested with can be loaded. In the Ionic App something prevents the loading of every epub file and the "renderTo" to be executed, because the book isn't opened. No error is reported on the console. I hope I can investigate and elaborate it tomorrow.

Any hints?
