### ISSUE TITLE
Rendering zipped Epubs with Cordova

### ISSUE THREAD

**Issue by Emmy02** [futurepress/epub.js#215]
Hi, I 'm developing a Web application, using cordova and ionic. I has tried different's ways to make epubjs work on a view, I can get the book's metadata, but I Can´t render de book. Any Ideas how to fix it!. Thanks..

**Comment by fchasen** [comment]
Could you share how you are requesting the epubs from cordova? Are they local or on a remote server?

**Comment by pwpvinci** [comment]
Hi, I am also use cordova and ionic to do the same thing. In advance, I can render the book since I unzip the epub file as a folder then it successfully render it. I think this could help Emmy02. However, I include the JSZip as the document's hierarchy but still cannot read epub directly. As well as Emmy02 said, it can successfullu load the metadata and no error reported, but it cannot render to the div.

**Comment by fchasen** [comment]
Possibly related to https://github.com/futurepress/epub.js/issues/272

**Comment by JakeHartnell** [comment]
See #272. Closing but feel free to reopen if this is still relevant.
