### ISSUE TITLE
Several examples don't work

### ISSUE THREAD

**Issue by outsideMyBox** [futurepress/epub.js#227]
Hi,

I tried the examples from http://futurepress.github.io/epub.js/ and 2 of them don't work (on Chrome 43 at least)

**mathml.html**  (nothing shown)
![epubjs-mathml](https://cloud.githubusercontent.com/assets/567748/8185082/567d91d0-1442-11e5-9c3c-046d2c909fe8.png)

**hypothesis.html** (nothing shown)
![epubjs-hypothesis](https://cloud.githubusercontent.com/assets/567748/8185109/9a9af042-1442-11e5-82dd-c5f5f84789cd.png)

I'm particularly interested to use annotations. Are they still supported or is it just an issue with the example?
I also saw this [other ticket](https://github.com/futurepress/epub.js/issues/197) but it doesn't clarify where the problem comes from.

**Comment by ShiYw** [comment]
it seems to be.
problems are probably caused by the mistaken js filenames.
for example:
in example Pagination   [examples/pagination.html]
in line 14 :   <script src="../libs/zip/zip-fs.js"></script>
                                                     ^     (i can hardly find it,so did my browser)
in line 15 :   <script src="../libs/zip/zip-ext.js"></script>
                                                            (the same)
there're some more,so in other examples like Mathml.

I don't know wheather it resulted from my wrong setting,or the project itself.
I hope it could be fixed ,or if i caused it,tell me.

BTW,the lib is great!

**Comment by ShiYw** [comment]
I don't know,but,today,the page somehow works.
I think it's no a bug,but the settings.
