### ISSUE TITLE
Page Breaks

### ISSUE THREAD

**Issue by ajrbyers** [futurepress/epub.js#261]
Hello!

We've started typesetting epubs as a single file and have noticed that epub.js is now not starting each chapter on a new page.

![screen shot 2015-08-27 at 15 38 48](https://cloud.githubusercontent.com/assets/8321378/9523440/e54a7cc6-4cd1-11e5-9f8a-a3df76cd6576.png)

Is this intentional or are we doing something wrong?

Live example: http://www.luminosoa.org/site/books/read/2/255/place-of-devotion/#epubcfi(/6/4[UCP-002-Sarbadhikary.xhtml]!4[UCP-002-Sarbadhikary]/2/1690/1:131)

Thanks!

**Comment by fchasen** [comment]
I recommend against combining all the chapters into a single file, as it will slow load times down.

However to break on chapters of a combined file you will need to add some css to the epubs or via a hook.

In the case of the example you sent the chapter breaks a `p` elements with `CN`, so the following css will break on those.
```css
.cn {       
        -webkit-column-break-before: always;
	break-before: column;
}
```
http://www.quirksmode.org/css/columns/breaks.html

Ideally though you would wrap each chapter in a `section` tag, so that the following `h1` tags make semantic sense.
