### ISSUE TITLE
Cannot Play Audio on Android

### ISSUE THREAD

**Issue by isamson72** [futurepress/epub.js#300]
I am having no luck to play audible epub3 books on android
Animations working fine
sound is missing only on android device, working fine on IOS.

can anyone let me know what to do?

**Comment by fchasen** [comment]
Not sure, strange that it would not work on Android. Do you have an example epub to test with?

**Comment by yinhaibo** [comment]
I can play audio and video in android devices using epub.js + cordova.
BUT I must move entry epub book(include html, audio and video files) to data directory instead of app dir.

If you using browser to access a epub file from server, It should be work fine.
You can check error log by inspect devices using chrome. may be some error in your script.
please refer to:(https://developers.google.com/chrome/mobile/docs/debugging)
