### ISSUE TITLE
Needs Contributors Guide

### ISSUE THREAD

**Issue by JakeHartnell** [futurepress/epub.js#346]
This includes things like where we write documentation (in the wiki for example), where the open channels for discussion are, the road map, etc.

Suggestions of good examples to base our contributors guide off of would be welcome.

**Comment by gerhardsletten** [comment]
There should be added more "admins" for this project as well, wright now there is 9 pull requests, the oldest about one month ago.  When people wants to contribute its important that they dont wait to long. Maybe @fchasen could need some help?

**Comment by fchasen** [comment]
Agreed!

Apologizes that it's taking so long to accept those pull requests. They are grouped together, for the most part, and are large changes. It is going to take some time to review them.

**Comment by gerhardsletten** [comment]
Hi @fchasen thats great, but would it not be better if more people was added as owners or admins of this project, so its not only depends on your time? 

The last fall I was reviewing an alternative epub-reader for a norwegian digital bookseller, we had a own developed html5 reader written some years ago, but after an major ios update we got serious issues, so we decided to go for an alternative. The true options was either ReadiumJS and Epub.js, and I found this alternative the most easies to integrate into their bookshelf.

At least in Scandinavia social DRM (water-mark) has been the main solution for publishers and they are moving away for Adobe DRM. Write now greater markeds as Germany is also in the move, and I think Adobe have big fears of loosing a lot of licence income so they have start to threaten ebooks-readers using their Reading SDK, as they meen using a "alternative DRM" (water-mark) is against their agreement. Most of their income is from a $0.20 fee for each book sold with Adobe DRM..

So as Adobe is loosing the grip on the marked there will be more companies looking for an alternative, so I might be a good moment go get some more people taking part in this project.

When it come to my wishes for what epub.js could be:

* a new version build around commenJS so it plays well with webpack, browserify and npm, maybe should the library be more diveded up into smaller modules, so more people can use and contribute to parts of the application
* Build with the next JS standard ES6 and with transpiled with Babel
* Could shadowDOM/react-ish or canvas be utilized for faster renders
* Focus on a good epub-rendering with a good and simple api (get / set reading position and prev/next page) over the ability to add fancy stuff into the pages

**Comment by fchasen** [comment]
Fantastic to hear that and thanks for sharing your those wishes, they reflect the direction that epub.js is headed.

Specifically in v0.3:
* API should be stabilized soon, but so far it is siginificantly cleaned up: https://github.com/futurepress/epub.js/blob/v0.3/API.js
* Builds are created using browserify and commonjs modules are used in the src with the goal of compatibility with Node in the near future. (using JSDom and a to be determined request library)
* Really easy to run and create tests using Mochify
* Rendering is separated from the epub loading / parsing so you should be able to register new types of renderers (for instance one that use React)
* Reader app will be a separate repo and hopefully will start getting the bug fixes it deserves.

After these changes land in master, the big push is going to be on documentation and tests so that contributions are easy to merge in the future.

This next version is almost ready for people to start testing, and I'll going to make sure to release a compatibility script before moving it to master so that upgrading shouldn't be too painful.

As for es6, I'm not quite ready to make the leap but would consider it in the future.

**Comment by MifRea1** [comment]
I've reviewed [some](https://github.com/futurepress/epub.js/blob/master/src/book.js) source files and found them to be a little dirty: indent spaces mixed with tabs, indent size switches between 2 and 4 (and probably 3). Maybe we should use a code [style guide](https://github.com/mozilla/pdf.js/wiki/Style-Guide)?
