### ISSUE TITLE
Mobile device browser

### ISSUE THREAD

**Issue by imperio001** [futurepress/epub.js#515]
Does any one know hot to show the ePub in full screen ?

**Comment by MaheshSinghSawant** [comment]
I'm assuming you want to remove status bar and navigation bar?
Since the title says mobile device browser, i assume it is safari?
if so maybe you can try this:
<meta name="apple-mobile-web-app-capable" content="yes" /> 
<meta name="viewport" content="width=device-width, initial-scale=1.0">

As for android i am not sure but you can look at this: 
http://stackoverflow.com/questions/7517352/fullscreen-web-app-for-android

I implemented full-screen in cordova using this plugin: https://github.com/mesmotronic/cordova-plugin-fullscreen

For Android: https://developer.android.com/training/system-ui/status.html
https://developer.android.com/training/system-ui/navigation.html

**Comment by fchasen** [comment]
@MaheshSinghSawant Thanks for those links!
