### ISSUE TITLE
How to find out if an element referenced by an epubcfi is currently visible/displayed

### ISSUE THREAD

**Issue by janmech** [futurepress/epub.js#627]
Hi All,
I realized that when recalling a bookmark link in the reader (by clicking on the bookmarked cfi) the actual epubcfi used in the url may be changed according to window size (and probably other parameters).
This means, when adding e.g. a bookmark in fullscreen view and recalling it in non fullscreen i cannot determine weather the current page is bookmarked or not. ( getCurrentLocationCfi() will return the epubcfi from the url.
Is there a way to detemine if the element referenced by an epubcfi is currently displayed/visible in the reader? E.q. to get the the first and the last epubcfi currently visible.

Thanks in advance!!!!

Jan

**Comment by janmech** [comment]
After digging a bit more i found the solution:

EPUBJS.Renderer.getVisibleRangeCfi() returns the first and last ebubcfi currently visible. On this base I can compare if any given ebubcfi is within that visible range.

**Comment by LordKayBanks** [comment]
@janmech 
can you please help out on how to get all the html Elements on the visible Screen (not the whole DOM).
i was thinking there has to be a way to get it from the " the first and last epubcfi currently visible".
i tried but cant figure it out.
thanks

**Comment by janmech** [comment]
@LordKayBanks 
I am not sure if the epubcfi will be helpful for this as it refers to the source-XMLs of the epub and not to their HTML/DOM representation in the reader. There may be something in the parser, but I am quite new to this as well and still exploring....

**Comment by LordKayBanks** [comment]
thanks for you swift response, i have been digging into this nonstop for over 3 weeks now.
i just want to get the reference to DOM elements that are currently on the screen.
so sad no one is replying to this feeds

**Comment by Aryesh-M** [comment]
Hello, is there a way to get only the currently displayed contents on the screen. Actually, I am building a search functionality in an ePub file (which of course has used epub.js). In that, I am highlighting all the words match will the searched string. I am successful to go to the next occurrence section-wise (i.e., it displays the next section when I want to find the next occurrence).
The problem is that it does not display the next page event if it has the perfect match (I have to manually go to that page by side arrows). So any idea? @fchasen.
