### ISSUE TITLE
Right edge of the text is getting cut.

### ISSUE THREAD

**Issue by itsvick** [futurepress/epub.js#669]
The text looks perfect on the first page when the user clicks on the next button to change the page the text also moves forward (from left to right) but the width of the text is not getting changed this results into cutting the right edge.

We have debugged this issue, we are not using spreads and used single page still it using `transform`.

Please refer attached screenshot.
#Reference https://github.com/futurepress/epub.js/issues/364
![screen shot 2017-10-10 at 4 41 58 pm](https://user-images.githubusercontent.com/20536805/31433857-3e1874aa-ae98-11e7-8349-d503ac98c136.png)

**Comment by pegues** [comment]
I've been experiencing the same problem, and haven't found a fix yet. I came across this, but doesn't help either: https://github.com/futurepress/epub.js/issues/162

**Comment by rohitpal99** [comment]
Yes. I would love to know the solution to this as well.

**Comment by vinukumar-vs** [comment]
Any update on this issue or any workaround to handle this problem?

**Comment by cmroanirgo** [comment]
If what you're seeing is each page being off by 1 pixel, so that by the 5th page, you're 5 pixels out then there is some code in src/render_iframe.js which seems to be the culprit. I commented it out in a forked copy. See this commit:

https://github.com/cmroanirgo/epub.js/commit/091fe4adb509f8b7ff6f8ae41c4cccaa931d404a

**Comment by fchasen** [comment]
I think that work around can be safely removed for v0.2, as it is no longer used in v0.3. I'll test a bit more and remove it.

**Comment by itsvick** [comment]
@cmroanirgo, unfortunately, it's still not working.
@fchasen

**Comment by cmroanirgo** [comment]
My fork (which is part of a larger project), also:
1. Resizes the `#viewer` so that it aligns with pixels. Perfectly.
2. On mobile devices, I switch to a 'fixed' size rather than using variable sizing. There's a few hoops jumped through to ensure that.

These two points are what I implemented, which *largely* fixed the problem, but still had the issue on Safari (iOS and OSX). The commit I mention above was a final fix for those. I haven't gone back and tested by removing the two points listed here.

**Comment by luisaccedo** [comment]
@cmroanirgo, unfortunately, it's doesn't work for me either

**Comment by Numilog** [comment]
Hi all, 
I have the same problem since Tag [v0.2.15](https://github.com/futurepress/epub.js/tree/v0.2.15)
([v0.2.14](https://github.com/futurepress/epub.js/tree/v0.2.15)) is working

**Comment by prsolucoes** [comment]
Any solution from latest version of epubjs?

**Comment by askilondz** [comment]
I've only been able to resolve this by passing the width and height to the ePub object and then setting the same width on the #book object in css dynamically.
````javascript
let bookContainer = this.element.nativeElement.querySelector('#book');
this.readerWidth = bookContainer.clientWidth;
this.readerHeight = this.platform.height() * .96;
this.reader = ePub(this.ebook.file, { width: this.readerWidth, height: this.readerHeight });
````
````html
<div id="book" [style.width.px]="readerWidth"></div>
````
Also since setting a padding or margin on the book messes up the formatting on page turns, I put the book in a wrapper where I set a width on it that works as the padding.
````html
<div class="book-wrapper">
    <div id="book" [style.width.px]="readerWidth"></div>
</div>
````
````css
.book-wrapper {
    width: 90%;
    height: 100%;
    margin: 20px auto;
 }
        
#book {
    z-index: 0;
    text-align: center;

    div {
         margin: 0 auto;
         height: 96%;
    }
}
````
