### ISSUE TITLE
Problem with scrolled-continuous reader

### ISSUE THREAD

**Issue by Cifyger** [futurepress/epub.js#845]
If i use the scrolled-continuous flow the iframe height is to small to display the whole page. This results in a cut off of the last paragraph of a page.

I were able to create a workaround but i dont think this should be necessary.

      /****** Small Iframe Bug workaround */
      let contentHeight: number = this.rendition.getContents()[0].scrollHeight();
      document.getElementsByTagName("iframe")[0].style.height = contentHeight + 'px';
      let el = document.getElementsByClassName('epub-container')[0];
      el.setAttribute('style', 'height: auto;');
      let el2 = document.getElementsByClassName('epub-view')[0];
      el2.setAttribute('style', 'height: auto;');
      /* Small Iframe Bug workaround ******/

**Comment by danielweck** [comment]
For what it's worth, Readium implements complex heuristics in order to handle documents that have a variable height over time. It is not uncommon for a document's dimensions to "stabilize" after a few milliseconds, depending on asynchronous behaviours such as font loading, media queries, etc. It is also not uncommon for a document's dimensions to change during the reading experience (at any arbitrary time), because of user interaction (e.g. the HTML "details" / "summary" markup which expands / collapses DOM fragments). One possible technique to address this issue is to instantiate a "resize sensor" for each loaded document, then throttle or debounce the "resize" events to trigger a layout pass at appropriate times. Note that this mechanism is also applicable to paginated reflowable documents, not just scroll views (e.g. to re-calculate the CSS columns).

**Comment by fchasen** [comment]
After trying a few approaches, we settled on a simple poll for resize here: https://github.com/futurepress/epub.js/blob/master/src/contents.js#L443

It might be reporting an incorrect height - @Cifyger  do you have an example you could share?

**Comment by emileae** [comment]
I'm experiencing the same issue, content height is a bit larger than iframe and epub container height.

**Comment by emileae** [comment]
> Made a codepen to illustrate the issue: https://codepen.io/fchasen/pen/NEKWPj
> 
> The `margin-top` of the `h2` isn't included in the height returned by `getBoundingClientRect()`
> 
> I've added the top to the height to fix it here: [3bf1501](https://github.com/futurepress/epub.js/commit/3bf150163c553335902b2d242e871da75b847782)

@fchasen thanks a million, I've made the change locally and its fixed the issue for me

**Comment by Cifyger** [comment]
> Made a codepen to illustrate the issue: https://codepen.io/fchasen/pen/NEKWPj
> 
> The `margin-top` of the `h2` isn't included in the height returned by `getBoundingClientRect()`
> 
> I've added the top to the height to fix it here: [3bf1501](https://github.com/futurepress/epub.js/commit/3bf150163c553335902b2d242e871da75b847782)

Also changed this localy and it solved my problem. Thanks alot.

**Comment by fchasen** [comment]
Deployed with `epubjs@0.3.79`
